from django.db import models

class Customer(models.Model):
    C_ID = models.CharField(max_length=20, primary_key=True)
    CUST_FIRST_NAME = models.CharField(max_length=50)
    CUST_MIDDLE_NAME = models.CharField(max_length=50, blank=True, null=True)
    CUST_LAST_NAME = models.CharField(max_length=50)
    FULL_NAME = models.CharField(max_length=150)
    CUST_DOB = models.DateField()
    GENDER = models.CharField(max_length=1, choices=[('M', 'Male'), ('F', 'Female')])
    EMPLOYMENT_STATUS = models.CharField(max_length=20)
    EMPLOYERSNAME = models.CharField(max_length=100)
    SALARY_PER_MONTH = models.DecimalField(max_digits=10, decimal_places=2)
    RISKRATING = models.CharField(max_length=10)
    PRIMARY_SOL_ID = models.CharField(max_length=10)
    MARITAL_STATUS = models.CharField(max_length=10)
    OCCUPATION = models.CharField(max_length=50)
    BLACKLISTED = models.BooleanField(default=False)
    RELATIONSHIPOPENINGDATE = models.DateField()
    CUSTOMERNREFLG = models.BooleanField(default=False)
    CUSTOMERMINOR = models.BooleanField(default=False)
    STAFFFLAG = models.BooleanField(default=False)
    STAFFEMPLOYEEID = models.CharField(max_length=20, blank=True, null=True)
    LAST_TRAN_DATE = models.DateField()
    KYC_LAST_REVIEW = models.DateField(blank=True, null=True)
    INTRODUCERNAME = models.CharField(max_length=100, blank=True, null=True)
    EDUCATION = models.CharField(max_length=50, blank=True, null=True)
    NATIONALITY = models.CharField(max_length=10)
    CUST_COMMUNITY = models.CharField(max_length=50)
    CUST_HLTH = models.CharField(max_length=10)
    TDS_TBL = models.CharField(max_length=10)
    RATING = models.CharField(max_length=10)
    PAN = models.CharField(max_length=10)
    STATUS = models.CharField(max_length=10)
    REF_DESC = models.CharField(max_length=100, blank=True, null=True)
    CONSTITUTION_CODE = models.CharField(max_length=10)
    SEGMENTATION_CLASS = models.CharField(max_length=10)
    INTRODUCERID = models.CharField(max_length=20, blank=True, null=True)
    INTRODUCER_NAME = models.CharField(max_length=100, blank=True, null=True)
    INTROD_STATUS = models.CharField(max_length=10)
    PURGEREMARKS = models.CharField(max_length=100, blank=True, null=True)
    CARD_HOLDER = models.BooleanField(default=False)
    CUSTOMER_RELATIONSHIP_IN_DAY = models.IntegerField()
    DAYS_SINCE_FIRST_ACCT_CREATED = models.IntegerField()
    DAYS_SINCE_LAST_KYC_REVIEWED = models.IntegerField(blank=True, null=True)
    DAYS_SINCE_LAST_TRANSACTION = models.IntegerField()

    def __str__(self):
        return f"{self.FULL_NAME} ({self.C_ID})"

class Detail(models.Model):
    customer = models.OneToOneField(Customer, on_delete=models.CASCADE, primary_key=True)
    DOCUMENT_ID = models.IntegerField()
    DOCUMENT_TYPE = models.CharField(max_length=100)
    ISSUED_BY = models.CharField(max_length=100, blank=True, null=True)
    ISSUED_DATE = models.DateTimeField()
    VALIDITY_DATE = models.DateTimeField(blank=True, null=True)
    DOCUMENT_DESCRIPTION = models.CharField(max_length=255)
    COUNTRYOFISSUE = models.CharField(max_length=10)
    SPOUSE_NAME = models.CharField(max_length=100, blank=True, null=True)
    FATHER_NAME = models.CharField(max_length=100, blank=True, null=True)
    MOTHER_NAME = models.CharField(max_length=100, blank=True, null=True)
    GRANDFATHER_NAME = models.CharField(max_length=100, blank=True, null=True)
    GRANDMOTHER_NAME = models.CharField(max_length=100, blank=True, null=True)
    SON_NAME = models.CharField(max_length=100, blank=True, null=True)
    DAUGHTER_NAME = models.CharField(max_length=100, blank=True, null=True)
    DAUGHTER_IN_LAW_NAME = models.CharField(max_length=100, blank=True, null=True)
    FATHER_IN_LAW_NAME = models.CharField(max_length=100, blank=True, null=True)
    COMMUNICATION_ID = models.IntegerField()
    COMMUNICATION_TYPE = models.CharField(max_length=50)
    PHONENO = models.CharField(max_length=15)
    PHONENOLOCALCODE = models.CharField(max_length=15)
    PHONENOCOUNTRYCODE = models.CharField(max_length=5)
    PREFERREDFLAG = models.CharField(max_length=1, choices=[('Y', 'Yes'), ('N', 'No')])
    EMAIL = models.EmailField(blank=True, null=True)
    ADDRESSID = models.IntegerField()
    ADDRESS_TYPE = models.CharField(max_length=50)
    ADDRESS_LINE = models.CharField(max_length=255)
    CITY = models.CharField(max_length=100)
    PROVINCE = models.CharField(max_length=100)
    ZIP = models.CharField(max_length=10)
    COUNTRY = models.CharField(max_length=10)
    IS_PREFERRED = models.CharField(max_length=1, choices=[('Y', 'Yes'), ('N', 'No')])
    IS_ACTIVE = models.CharField(max_length=1, choices=[('Y', 'Yes'), ('N', 'No')])

    def __str__(self):
        return f"Document ID: {self.DOCUMENT_ID}, Document Type: {self.DOCUMENT_TYPE}"
