# Generated by Django 5.0.7 on 2024-07-24 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('customer_type', models.CharField(choices=[('individual', 'Individual'), ('legal', 'Legal')], default='individual', max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('risk_rating', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=7)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dormant', 'Dormant')], default='active', max_length=8)),
                ('average_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
    ]
