# Generated by Django 5.0.7 on 2024-09-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audience', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='audience',
            table='Audience',
        ),
    ]
